### ISSUE TITLE
Add contributing section on README

### ISSUE THREAD

**Issue by LTKills** [LTKills/task-sprinter#10]
I believe the contributing section should have

* Instructions on how to correctly get an issue
* What to put in PRs (make an individual pull request for each suggestion)
* How to name PRs (the pull request and commit should have a useful title)
* Check your spelling and grammar.
* Add your nick to CONTRIBUTORS.md

Add anything else you judge important

**Comment by senatormailman** [comment]
Hi, I would like to contribute to this. I can elaborate on how I feel to implement your points:

1. First, I am not sure which you would prefer, but I was thinking of adding a CONTRIBUTE.md file to show the instructions. I can also just add this to README.md. Let me know which you would prefer.
2. **Instructions on how to correctly get an issue** I would showcase how to find issues for your project (Probably link to your open issues in the guide) and then show that you must notify the maintainer on the specified issue. Much like what I am doing now.
3. **What to put in PRs (make an individual pull request for each suggestion)** I would specify with an example. (Say there is an issue you are resolving, but you also have a change for an issue you haven't claimed. The appropriate order would be to only perform a pull request for the issue you are addressing.)
4. I was also thinking of linking to [Digital Ocean's guide for making pull requests](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) somewhere as it has been really helpful for keeping repos in a logical order.

Let me know if you have any suggestions and I will get to work on this if you approve.

**Comment by senatormailman** [comment]
I'm sorry I neglected a section!

**How to name PRs (the pull request and commit should have a useful title)**

I would include mentioning the issue number either in the title or description of the PR as well as succinctly titling the PR (Example: "Added Contribution Guide" or "Fixed Typos on <FILE>") which does also tie in to why PRs should be Individual.

**Comment by gmelodie** [comment]
Closed by #12
