### ISSUE TITLE
Write contribution guidelines on README.md

### ISSUE THREAD

**Issue by LTKills** [LTKills/task-sprinter#3]
Guidelines need to be agreed first and then written

**Comment by NotoriousRebel** [comment]
Do you have a set of guidelines?

**Comment by LTKills** [comment]
I don't, do you have any ideas? I believe creating a virtualenv and running the program in an unified fashion is nice because it avoids different versions of python/libraries to cause compatibility issues

**Comment by NotoriousRebel** [comment]
A virtualenv is fine; however, if someone just wants to git clone and run it right out the box that might take a little longer than they want. But for the sake of uniformity that's good.

**Comment by LTKills** [comment]
Yeah I was thinking the virtualenv as a form of "test", for example, one that wants to develop should do so by creating a virtualenv configured as listed on contributions.md to avoid troubles with other developers. I believe for running purposes it should indeed work out of the box

**Comment by NotoriousRebel** [comment]
I can help out with the contributions.md.

**Comment by LTKills** [comment]
Closed in #7
