### ISSUE TITLE
Add routine and task documentation

### ISSUE THREAD

**Issue by gmelodie** [LTKills/task-sprinter#4]
The files with code regarding routines and tasks is in the `cli` branch. 

Routines are lists of tasks with additional information (only description and total time so far)

Each task has its own description and the time one has to complete it.

Routines end when their last task ends, a task ends when it is marked as finished or the time to complete it runs out.

**Comment by diproray** [comment]
I will work on this for Hacktoberfest!

**Comment by LTKills** [comment]
Yay! thanks!

**Comment by diproray** [comment]
Just to understand what I have to do a bit further, I see in the `src` folder of `cli` branch, a few python files with placeholder functions. Would you like me to write the documentation for these functions using reStructuredText?

**Comment by LTKills** [comment]
No need, a more high level explaination of the concepts is fine. I believe writting code-related documentation now can cause trouble in probable future refactorings.

**Comment by diproray** [comment]
Okay, cool! I'll get started on this!

**Comment by diproray** [comment]
#8
